version: '3.9'
services:
  drone_server:
    image: drone/drone
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/lib/drone:/data
      - drone:/var/lib/drone
    env_file:
      - ./.env
    environment:
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_TEXT=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true
      - DRONE_LOGS_TRACE=true
    container_name: drone_server

volumes:
  drone:

